version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_CONTAINER_NAME:-localstack_main}"
    image: localstack/localstack
    ports:
      - "8081:8080" # LocalStack Web UI
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=dynamodb,sns,lambda,apigateway,cloudformation,logs,iam # Services to be started
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount Docker socket for LocalStack to interact with Docker
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge